name: dingoprototype
description: A Dingo! prototype

version: 1.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_calendar_carousel: ^1.4.11
  crypto: ^2.1.3
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.19+9
  simple_animations: ^1.3.9
  charts_flutter: ^0.9.0
  cloud_firestore: ^0.13.4+1
  firebase_auth: 0.15.3
  firebase_core: 0.4.4
  firebase_database: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/weather/
    - images/announcementMenu/
    - images/fingerprintIcon/